/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ArtistInterface extends ethers.utils.Interface {
  functions: {
    "getByAddress(address)": FunctionFragment;
    "getSignatureAttributes(address)": FunctionFragment;
    "isFundsRedirectAllowedFor(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getByAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignatureAttributes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isFundsRedirectAllowedFor",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignatureAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFundsRedirectAllowedFor",
    data: BytesLike
  ): Result;

  events: {};
}

export class Artist extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ArtistInterface;

  functions: {
    getByAddress(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      userId: BigNumber;
      artistAddress: string;
      name: string;
      dada_portrait_uri: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
    }>;

    "getByAddress(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      userId: BigNumber;
      artistAddress: string;
      name: string;
      dada_portrait_uri: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
    }>;

    getSignatureAttributes(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    "getSignatureAttributes(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    isFundsRedirectAllowedFor(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isFundsRedirectAllowedFor(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  getByAddress(
    _artistAddress: string,
    overrides?: CallOverrides
  ): Promise<{
    userId: BigNumber;
    artistAddress: string;
    name: string;
    dada_portrait_uri: string;
    0: BigNumber;
    1: string;
    2: string;
    3: string;
  }>;

  "getByAddress(address)"(
    _artistAddress: string,
    overrides?: CallOverrides
  ): Promise<{
    userId: BigNumber;
    artistAddress: string;
    name: string;
    dada_portrait_uri: string;
    0: BigNumber;
    1: string;
    2: string;
    3: string;
  }>;

  getSignatureAttributes(
    _artistAddress: string,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: string;
    2: string;
    3: string;
  }>;

  "getSignatureAttributes(address)"(
    _artistAddress: string,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: string;
    2: string;
    3: string;
  }>;

  isFundsRedirectAllowedFor(
    _artistAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isFundsRedirectAllowedFor(address)"(
    _artistAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getByAddress(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      userId: BigNumber;
      artistAddress: string;
      name: string;
      dada_portrait_uri: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
    }>;

    "getByAddress(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      userId: BigNumber;
      artistAddress: string;
      name: string;
      dada_portrait_uri: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
    }>;

    getSignatureAttributes(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    "getSignatureAttributes(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    isFundsRedirectAllowedFor(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isFundsRedirectAllowedFor(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getByAddress(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getByAddress(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSignatureAttributes(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSignatureAttributes(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isFundsRedirectAllowedFor(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isFundsRedirectAllowedFor(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getByAddress(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getByAddress(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSignatureAttributes(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSignatureAttributes(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isFundsRedirectAllowedFor(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isFundsRedirectAllowedFor(address)"(
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
