/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Artist } from "./Artist";

export class ArtistFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): Artist {
    return new Contract(address, _abi, signerOrProvider) as Artist;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_artistAddress",
        type: "address",
      },
    ],
    name: "getByAddress",
    outputs: [
      {
        name: "userId",
        type: "uint256",
      },
      {
        name: "artistAddress",
        type: "address",
      },
      {
        name: "name",
        type: "string",
      },
      {
        name: "dada_portrait_uri",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_artistAddress",
        type: "address",
      },
    ],
    name: "getSignatureAttributes",
    outputs: [
      {
        name: "",
        type: "string",
      },
      {
        name: "",
        type: "string",
      },
      {
        name: "",
        type: "string",
      },
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_artistAddress",
        type: "address",
      },
    ],
    name: "isFundsRedirectAllowedFor",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
