/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CollectibleModelInterface extends ethers.utils.Interface {
  functions: {
    "cfoAddress()": FunctionFragment;
    "collectibles(uint256)": FunctionFragment;
    "ceoAddress()": FunctionFragment;
    "collectiblePrintNumber(uint256)": FunctionFragment;
    "setWithdrawalAddress(address)": FunctionFragment;
    "setCEO(address)": FunctionFragment;
    "setCOO(address)": FunctionFragment;
    "collectibleIssuedTime(uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "setCFO(address)": FunctionFragment;
    "pushCollectible(uint256,uint256)": FunctionFragment;
    "paused()": FunctionFragment;
    "withdrawBalance()": FunctionFragment;
    "emitCollectibleIssuedEvent(address,address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "collectionBaseItemPriceOf(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "m_asset()": FunctionFragment;
    "upgradeCollectionBaseItemModelContract(address)": FunctionFragment;
    "pause()": FunctionFragment;
    "owner()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "isCollectionBaseItemActive(uint256)": FunctionFragment;
    "upgradeExhibitModelContract(address)": FunctionFragment;
    "collectibleInfo(uint256)": FunctionFragment;
    "cooAddress()": FunctionFragment;
    "m_collectionBaseItem()": FunctionFragment;
    "upgradeAssetModelContract(address)": FunctionFragment;
    "setAuthorizationStatus(address,bool)": FunctionFragment;
    "withdrawalAddress()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "getCollectionBaseItemId(uint256)": FunctionFragment;
    "m_exhibit()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cfoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectibles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ceoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectiblePrintNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setCEO", values: [string]): string;
  encodeFunctionData(functionFragment: "setCOO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "collectibleIssuedTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "setCFO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pushCollectible",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emitCollectibleIssuedEvent",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionBaseItemPriceOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "m_asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeCollectionBaseItemModelContract",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isCollectionBaseItemActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeExhibitModelContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "collectibleInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cooAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "m_collectionBaseItem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAssetModelContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizationStatus",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionBaseItemId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "m_exhibit", values?: undefined): string;

  decodeFunctionResult(functionFragment: "cfoAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectibles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ceoAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectiblePrintNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCEO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCOO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectibleIssuedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCFO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pushCollectible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitCollectibleIssuedEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionBaseItemPriceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "m_asset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeCollectionBaseItemModelContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCollectionBaseItemActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeExhibitModelContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectibleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cooAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "m_collectionBaseItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAssetModelContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionBaseItemId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "m_exhibit", data: BytesLike): Result;

  events: {
    "CollectibleIssued(address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "ContractUpgrade(address)": EventFragment;
    "Paused()": EventFragment;
    "Unpaused()": EventFragment;
    "Pause()": EventFragment;
    "Unpause()": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollectibleIssued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractUpgrade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Pause"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpause"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class CollectibleModel extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CollectibleModelInterface;

  functions: {
    cfoAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    collectibles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      collectionBaseItemId: BigNumber;
      issuedTime: BigNumber;
      printNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    "collectibles(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      collectionBaseItemId: BigNumber;
      issuedTime: BigNumber;
      printNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    ceoAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    collectiblePrintNumber(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "collectiblePrintNumber(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setCEO(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setCOO(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    collectibleIssuedTime(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "collectibleIssuedTime(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    unpause(overrides?: Overrides): Promise<ContractTransaction>;

    "unpause()"(overrides?: Overrides): Promise<ContractTransaction>;

    setCFO(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    pushCollectible(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "pushCollectible(uint256,uint256)"(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "paused()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    withdrawBalance(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawBalance()"(overrides?: Overrides): Promise<ContractTransaction>;

    emitCollectibleIssuedEvent(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "emitCollectibleIssuedEvent(address,address,uint256,uint256,uint256,uint256)"(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    collectionBaseItemPriceOf(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "collectionBaseItemPriceOf(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    m_asset(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "m_asset()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    upgradeCollectionBaseItemModelContract(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeCollectionBaseItemModelContract(address)"(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    pause(overrides?: Overrides): Promise<ContractTransaction>;

    "pause()"(overrides?: Overrides): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    isOwner(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "isOwner()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    isCollectionBaseItemActive(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isCollectionBaseItemActive(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    upgradeExhibitModelContract(
      newExhibitModelContractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeExhibitModelContract(address)"(
      newExhibitModelContractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    collectibleInfo(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: string;
      9: string;
    }>;

    "collectibleInfo(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: string;
      9: string;
    }>;

    cooAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "cooAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    m_collectionBaseItem(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "m_collectionBaseItem()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    upgradeAssetModelContract(
      newAssetModelContractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeAssetModelContract(address)"(
      newAssetModelContractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawalAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "withdrawalAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getCollectionBaseItemId(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getCollectionBaseItemId(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    m_exhibit(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "m_exhibit()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  cfoAddress(overrides?: CallOverrides): Promise<string>;

  "cfoAddress()"(overrides?: CallOverrides): Promise<string>;

  collectibles(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    collectionBaseItemId: BigNumber;
    issuedTime: BigNumber;
    printNumber: BigNumber;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
  }>;

  "collectibles(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    collectionBaseItemId: BigNumber;
    issuedTime: BigNumber;
    printNumber: BigNumber;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
  }>;

  ceoAddress(overrides?: CallOverrides): Promise<string>;

  "ceoAddress()"(overrides?: CallOverrides): Promise<string>;

  collectiblePrintNumber(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "collectiblePrintNumber(uint256)"(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setWithdrawalAddress(
    _newWithdrawalAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setWithdrawalAddress(address)"(
    _newWithdrawalAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setCEO(_newCEO: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setCEO(address)"(
    _newCEO: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setCOO(_newCOO: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setCOO(address)"(
    _newCOO: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  collectibleIssuedTime(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "collectibleIssuedTime(uint256)"(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unpause(overrides?: Overrides): Promise<ContractTransaction>;

  "unpause()"(overrides?: Overrides): Promise<ContractTransaction>;

  setCFO(_newCFO: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setCFO(address)"(
    _newCFO: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  pushCollectible(
    _collectionBaseItemId: BigNumberish,
    _issuedTime: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "pushCollectible(uint256,uint256)"(
    _collectionBaseItemId: BigNumberish,
    _issuedTime: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  withdrawBalance(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawBalance()"(overrides?: Overrides): Promise<ContractTransaction>;

  emitCollectibleIssuedEvent(
    _collectibleOwner: string,
    _purchaser: string,
    _collectibleId: BigNumberish,
    _collectionBaseItemId: BigNumberish,
    _issuedTime: BigNumberish,
    _printNumber: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "emitCollectibleIssuedEvent(address,address,uint256,uint256,uint256,uint256)"(
    _collectibleOwner: string,
    _purchaser: string,
    _collectibleId: BigNumberish,
    _collectionBaseItemId: BigNumberish,
    _issuedTime: BigNumberish,
    _printNumber: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  collectionBaseItemPriceOf(
    _collectionBaseItemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "collectionBaseItemPriceOf(uint256)"(
    _collectionBaseItemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  m_asset(overrides?: CallOverrides): Promise<string>;

  "m_asset()"(overrides?: CallOverrides): Promise<string>;

  upgradeCollectionBaseItemModelContract(
    newCollectionBaseItemModelContractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeCollectionBaseItemModelContract(address)"(
    newCollectionBaseItemModelContractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  pause(overrides?: Overrides): Promise<ContractTransaction>;

  "pause()"(overrides?: Overrides): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  isCollectionBaseItemActive(
    _collectionBaseItemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isCollectionBaseItemActive(uint256)"(
    _collectionBaseItemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  upgradeExhibitModelContract(
    newExhibitModelContractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeExhibitModelContract(address)"(
    newExhibitModelContractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  collectibleInfo(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
    8: string;
    9: string;
  }>;

  "collectibleInfo(uint256)"(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
    8: string;
    9: string;
  }>;

  cooAddress(overrides?: CallOverrides): Promise<string>;

  "cooAddress()"(overrides?: CallOverrides): Promise<string>;

  m_collectionBaseItem(overrides?: CallOverrides): Promise<string>;

  "m_collectionBaseItem()"(overrides?: CallOverrides): Promise<string>;

  upgradeAssetModelContract(
    newAssetModelContractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeAssetModelContract(address)"(
    newAssetModelContractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setAuthorizationStatus(
    _authorizedAddress: string,
    _authorizedStatus: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAuthorizationStatus(address,bool)"(
    _authorizedAddress: string,
    _authorizedStatus: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawalAddress(overrides?: CallOverrides): Promise<string>;

  "withdrawalAddress()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getCollectionBaseItemId(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getCollectionBaseItemId(uint256)"(
    _collectibleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  m_exhibit(overrides?: CallOverrides): Promise<string>;

  "m_exhibit()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    cfoAddress(overrides?: CallOverrides): Promise<string>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<string>;

    collectibles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      collectionBaseItemId: BigNumber;
      issuedTime: BigNumber;
      printNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    "collectibles(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      collectionBaseItemId: BigNumber;
      issuedTime: BigNumber;
      printNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    ceoAddress(overrides?: CallOverrides): Promise<string>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<string>;

    collectiblePrintNumber(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectiblePrintNumber(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCEO(_newCEO: string, overrides?: CallOverrides): Promise<void>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCOO(_newCOO: string, overrides?: CallOverrides): Promise<void>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    collectibleIssuedTime(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectibleIssuedTime(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;

    setCFO(_newCFO: string, overrides?: CallOverrides): Promise<void>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    pushCollectible(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    "pushCollectible(uint256,uint256)"(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    withdrawBalance(overrides?: CallOverrides): Promise<void>;

    "withdrawBalance()"(overrides?: CallOverrides): Promise<void>;

    emitCollectibleIssuedEvent(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "emitCollectibleIssuedEvent(address,address,uint256,uint256,uint256,uint256)"(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    collectionBaseItemPriceOf(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectionBaseItemPriceOf(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    m_asset(overrides?: CallOverrides): Promise<string>;

    "m_asset()"(overrides?: CallOverrides): Promise<string>;

    upgradeCollectionBaseItemModelContract(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeCollectionBaseItemModelContract(address)"(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    isCollectionBaseItemActive(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isCollectionBaseItemActive(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    upgradeExhibitModelContract(
      newExhibitModelContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeExhibitModelContract(address)"(
      newExhibitModelContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    collectibleInfo(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: string;
      9: string;
    }>;

    "collectibleInfo(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: string;
      9: string;
    }>;

    cooAddress(overrides?: CallOverrides): Promise<string>;

    "cooAddress()"(overrides?: CallOverrides): Promise<string>;

    m_collectionBaseItem(overrides?: CallOverrides): Promise<string>;

    "m_collectionBaseItem()"(overrides?: CallOverrides): Promise<string>;

    upgradeAssetModelContract(
      newAssetModelContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeAssetModelContract(address)"(
      newAssetModelContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawalAddress(overrides?: CallOverrides): Promise<string>;

    "withdrawalAddress()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getCollectionBaseItemId(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCollectionBaseItemId(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    m_exhibit(overrides?: CallOverrides): Promise<string>;

    "m_exhibit()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    CollectibleIssued(
      collectibleOwner: string | null,
      purchaser: string | null,
      collectibleId: null,
      collectionBaseItemId: null,
      issuedTime: null,
      printNumber: null
    ): EventFilter;

    ContractUpgrade(newContract: null): EventFilter;

    Paused(): EventFilter;

    Unpaused(): EventFilter;

    Pause(): EventFilter;

    Unpause(): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    cfoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    collectibles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectibles(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ceoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    collectiblePrintNumber(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectiblePrintNumber(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setCEO(_newCEO: string, overrides?: Overrides): Promise<BigNumber>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setCOO(_newCOO: string, overrides?: Overrides): Promise<BigNumber>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    collectibleIssuedTime(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectibleIssuedTime(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides): Promise<BigNumber>;

    "unpause()"(overrides?: Overrides): Promise<BigNumber>;

    setCFO(_newCFO: string, overrides?: Overrides): Promise<BigNumber>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    pushCollectible(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "pushCollectible(uint256,uint256)"(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawBalance(overrides?: Overrides): Promise<BigNumber>;

    "withdrawBalance()"(overrides?: Overrides): Promise<BigNumber>;

    emitCollectibleIssuedEvent(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "emitCollectibleIssuedEvent(address,address,uint256,uint256,uint256,uint256)"(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    collectionBaseItemPriceOf(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectionBaseItemPriceOf(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    m_asset(overrides?: CallOverrides): Promise<BigNumber>;

    "m_asset()"(overrides?: CallOverrides): Promise<BigNumber>;

    upgradeCollectionBaseItemModelContract(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgradeCollectionBaseItemModelContract(address)"(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    pause(overrides?: Overrides): Promise<BigNumber>;

    "pause()"(overrides?: Overrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    isCollectionBaseItemActive(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isCollectionBaseItemActive(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeExhibitModelContract(
      newExhibitModelContractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgradeExhibitModelContract(address)"(
      newExhibitModelContractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    collectibleInfo(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectibleInfo(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cooAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "cooAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    m_collectionBaseItem(overrides?: CallOverrides): Promise<BigNumber>;

    "m_collectionBaseItem()"(overrides?: CallOverrides): Promise<BigNumber>;

    upgradeAssetModelContract(
      newAssetModelContractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgradeAssetModelContract(address)"(
      newAssetModelContractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawalAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "withdrawalAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getCollectionBaseItemId(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCollectionBaseItemId(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    m_exhibit(overrides?: CallOverrides): Promise<BigNumber>;

    "m_exhibit()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cfoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collectibles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collectibles(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ceoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collectiblePrintNumber(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collectiblePrintNumber(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setCEO(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setCOO(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    collectibleIssuedTime(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collectibleIssuedTime(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(overrides?: Overrides): Promise<PopulatedTransaction>;

    "unpause()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setCFO(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    pushCollectible(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "pushCollectible(uint256,uint256)"(
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawBalance(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawBalance()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    emitCollectibleIssuedEvent(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "emitCollectibleIssuedEvent(address,address,uint256,uint256,uint256,uint256)"(
      _collectibleOwner: string,
      _purchaser: string,
      _collectibleId: BigNumberish,
      _collectionBaseItemId: BigNumberish,
      _issuedTime: BigNumberish,
      _printNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    collectionBaseItemPriceOf(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collectionBaseItemPriceOf(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    m_asset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "m_asset()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    upgradeCollectionBaseItemModelContract(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeCollectionBaseItemModelContract(address)"(
      newCollectionBaseItemModelContractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    pause(overrides?: Overrides): Promise<PopulatedTransaction>;

    "pause()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isCollectionBaseItemActive(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isCollectionBaseItemActive(uint256)"(
      _collectionBaseItemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeExhibitModelContract(
      newExhibitModelContractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeExhibitModelContract(address)"(
      newExhibitModelContractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    collectibleInfo(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collectibleInfo(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cooAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cooAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    m_collectionBaseItem(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "m_collectionBaseItem()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeAssetModelContract(
      newAssetModelContractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeAssetModelContract(address)"(
      newAssetModelContractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawalAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "withdrawalAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getCollectionBaseItemId(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCollectionBaseItemId(uint256)"(
      _collectibleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    m_exhibit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "m_exhibit()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
