/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ExhibitModelInterface extends ethers.utils.Interface {
  functions: {
    "cfoAddress()": FunctionFragment;
    "setMetadataURI(uint256,string)": FunctionFragment;
    "ceoAddress()": FunctionFragment;
    "getPublished(uint256)": FunctionFragment;
    "setWithdrawalAddress(address)": FunctionFragment;
    "setCEO(address)": FunctionFragment;
    "setDescription(uint256,string)": FunctionFragment;
    "setCOO(address)": FunctionFragment;
    "getSplashURI(uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "getDescription(uint256)": FunctionFragment;
    "updateExhibit(uint256,uint256,uint256,bool,bool,string,string,string,string)": FunctionFragment;
    "setCFO(address)": FunctionFragment;
    "setSplashURI(uint256,string)": FunctionFragment;
    "paused()": FunctionFragment;
    "withdrawBalance()": FunctionFragment;
    "getName(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setPublished(uint256,bool)": FunctionFragment;
    "getExhibitsLength()": FunctionFragment;
    "pause()": FunctionFragment;
    "getAssetsTotal(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "getCreatedAt(uint256)": FunctionFragment;
    "createExhibit(uint256,uint256,string,string,string,string)": FunctionFragment;
    "getPrintsTotal(uint256)": FunctionFragment;
    "cooAddress()": FunctionFragment;
    "setAssetsTotal(uint256,uint256)": FunctionFragment;
    "getMetadataURI(uint256)": FunctionFragment;
    "exhibits(uint256)": FunctionFragment;
    "getActive(uint256)": FunctionFragment;
    "getExhibit(uint256)": FunctionFragment;
    "setAuthorizationStatus(address,bool)": FunctionFragment;
    "setActive(uint256,bool)": FunctionFragment;
    "withdrawalAddress()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "setPrintsTotal(uint256,uint256)": FunctionFragment;
    "setName(uint256,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cfoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMetadataURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ceoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublished",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setCEO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setDescription",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "setCOO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getSplashURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDescription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExhibit",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "setCFO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setSplashURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPublished",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getExhibitsLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAssetsTotal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCreatedAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createExhibit",
    values: [BigNumberish, BigNumberish, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrintsTotal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cooAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetsTotal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetadataURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exhibits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExhibit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizationStatus",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrintsTotal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setName",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "cfoAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ceoAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPublished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCEO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCOO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSplashURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExhibit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCFO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSplashURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExhibitsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetsTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createExhibit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrintsTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cooAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAssetsTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exhibits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getExhibit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrintsTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;

  events: {
    "ExhibitCreated(uint256,uint256,string)": EventFragment;
    "ContractUpgrade(address)": EventFragment;
    "Paused()": EventFragment;
    "Unpaused()": EventFragment;
    "Pause()": EventFragment;
    "Unpause()": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExhibitCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractUpgrade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Pause"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpause"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ExhibitModel extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ExhibitModelInterface;

  functions: {
    cfoAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    setMetadataURI(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMetadataURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    ceoAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    getPublished(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "getPublished(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setCEO(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDescription(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDescription(uint256,string)"(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setCOO(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getSplashURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getSplashURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    unpause(overrides?: Overrides): Promise<ContractTransaction>;

    "unpause()"(overrides?: Overrides): Promise<ContractTransaction>;

    getDescription(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getDescription(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    updateExhibit(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateExhibit(uint256,uint256,uint256,bool,bool,string,string,string,string)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setCFO(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSplashURI(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSplashURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "paused()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    withdrawBalance(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawBalance()"(overrides?: Overrides): Promise<ContractTransaction>;

    getName(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getName(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setPublished(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPublished(uint256,bool)"(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getExhibitsLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getExhibitsLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    pause(overrides?: Overrides): Promise<ContractTransaction>;

    "pause()"(overrides?: Overrides): Promise<ContractTransaction>;

    getAssetsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getAssetsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    isOwner(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "isOwner()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    getCreatedAt(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getCreatedAt(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    createExhibit(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createExhibit(uint256,uint256,string,string,string,string)"(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getPrintsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPrintsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    cooAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "cooAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    setAssetsTotal(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAssetsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getMetadataURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getMetadataURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    exhibits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: boolean;
      5: boolean;
      6: string;
      7: string;
      8: string;
      9: string;
    }>;

    "exhibits(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: boolean;
      5: boolean;
      6: string;
      7: string;
      8: string;
      9: string;
    }>;

    getActive(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "getActive(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    getExhibit(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: boolean;
      4: boolean;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;

    "getExhibit(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: boolean;
      4: boolean;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setActive(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setActive(uint256,bool)"(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawalAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "withdrawalAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPrintsTotal(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPrintsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setName(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setName(uint256,string)"(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  cfoAddress(overrides?: CallOverrides): Promise<string>;

  "cfoAddress()"(overrides?: CallOverrides): Promise<string>;

  setMetadataURI(
    _exhibitId: BigNumberish,
    _metadataURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMetadataURI(uint256,string)"(
    _exhibitId: BigNumberish,
    _metadataURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  ceoAddress(overrides?: CallOverrides): Promise<string>;

  "ceoAddress()"(overrides?: CallOverrides): Promise<string>;

  getPublished(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getPublished(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setWithdrawalAddress(
    _newWithdrawalAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setWithdrawalAddress(address)"(
    _newWithdrawalAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setCEO(_newCEO: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setCEO(address)"(
    _newCEO: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDescription(
    _exhibitId: BigNumberish,
    _description: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDescription(uint256,string)"(
    _exhibitId: BigNumberish,
    _description: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setCOO(_newCOO: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setCOO(address)"(
    _newCOO: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getSplashURI(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getSplashURI(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  unpause(overrides?: Overrides): Promise<ContractTransaction>;

  "unpause()"(overrides?: Overrides): Promise<ContractTransaction>;

  getDescription(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getDescription(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  updateExhibit(
    _exhibitId: BigNumberish,
    _assetsTotal: BigNumberish,
    _printsTotal: BigNumberish,
    _published: boolean,
    _active: boolean,
    _name: string,
    _description: string,
    _splashURI: string,
    _metadataURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateExhibit(uint256,uint256,uint256,bool,bool,string,string,string,string)"(
    _exhibitId: BigNumberish,
    _assetsTotal: BigNumberish,
    _printsTotal: BigNumberish,
    _published: boolean,
    _active: boolean,
    _name: string,
    _description: string,
    _splashURI: string,
    _metadataURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setCFO(_newCFO: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setCFO(address)"(
    _newCFO: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSplashURI(
    _exhibitId: BigNumberish,
    _splashURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSplashURI(uint256,string)"(
    _exhibitId: BigNumberish,
    _splashURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  withdrawBalance(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawBalance()"(overrides?: Overrides): Promise<ContractTransaction>;

  getName(_exhibitId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getName(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setPublished(
    _exhibitId: BigNumberish,
    _published: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPublished(uint256,bool)"(
    _exhibitId: BigNumberish,
    _published: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getExhibitsLength(overrides?: CallOverrides): Promise<BigNumber>;

  "getExhibitsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  pause(overrides?: Overrides): Promise<ContractTransaction>;

  "pause()"(overrides?: Overrides): Promise<ContractTransaction>;

  getAssetsTotal(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAssetsTotal(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  getCreatedAt(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getCreatedAt(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createExhibit(
    _assetsTotal: BigNumberish,
    _printsTotal: BigNumberish,
    _name: string,
    _description: string,
    _splashURI: string,
    _metadataURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createExhibit(uint256,uint256,string,string,string,string)"(
    _assetsTotal: BigNumberish,
    _printsTotal: BigNumberish,
    _name: string,
    _description: string,
    _splashURI: string,
    _metadataURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getPrintsTotal(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPrintsTotal(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cooAddress(overrides?: CallOverrides): Promise<string>;

  "cooAddress()"(overrides?: CallOverrides): Promise<string>;

  setAssetsTotal(
    _exhibitId: BigNumberish,
    _assetsTotal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAssetsTotal(uint256,uint256)"(
    _exhibitId: BigNumberish,
    _assetsTotal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getMetadataURI(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getMetadataURI(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  exhibits(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    assetsTotal: BigNumber;
    printsTotal: BigNumber;
    createdAt: BigNumber;
    published: boolean;
    active: boolean;
    name: string;
    description: string;
    splashURI: string;
    metadataURI: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: boolean;
    5: boolean;
    6: string;
    7: string;
    8: string;
    9: string;
  }>;

  "exhibits(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    assetsTotal: BigNumber;
    printsTotal: BigNumber;
    createdAt: BigNumber;
    published: boolean;
    active: boolean;
    name: string;
    description: string;
    splashURI: string;
    metadataURI: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: boolean;
    5: boolean;
    6: string;
    7: string;
    8: string;
    9: string;
  }>;

  getActive(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getActive(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getExhibit(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    assetsTotal: BigNumber;
    printsTotal: BigNumber;
    createdAt: BigNumber;
    published: boolean;
    active: boolean;
    name: string;
    description: string;
    splashURI: string;
    metadataURI: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: boolean;
    4: boolean;
    5: string;
    6: string;
    7: string;
    8: string;
  }>;

  "getExhibit(uint256)"(
    _exhibitId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    assetsTotal: BigNumber;
    printsTotal: BigNumber;
    createdAt: BigNumber;
    published: boolean;
    active: boolean;
    name: string;
    description: string;
    splashURI: string;
    metadataURI: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: boolean;
    4: boolean;
    5: string;
    6: string;
    7: string;
    8: string;
  }>;

  setAuthorizationStatus(
    _authorizedAddress: string,
    _authorizedStatus: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAuthorizationStatus(address,bool)"(
    _authorizedAddress: string,
    _authorizedStatus: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setActive(
    _exhibitId: BigNumberish,
    _active: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setActive(uint256,bool)"(
    _exhibitId: BigNumberish,
    _active: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawalAddress(overrides?: CallOverrides): Promise<string>;

  "withdrawalAddress()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPrintsTotal(
    _exhibitId: BigNumberish,
    _printsTotal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPrintsTotal(uint256,uint256)"(
    _exhibitId: BigNumberish,
    _printsTotal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setName(
    _exhibitId: BigNumberish,
    _name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setName(uint256,string)"(
    _exhibitId: BigNumberish,
    _name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    cfoAddress(overrides?: CallOverrides): Promise<string>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<string>;

    setMetadataURI(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMetadataURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ceoAddress(overrides?: CallOverrides): Promise<string>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<string>;

    getPublished(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getPublished(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCEO(_newCEO: string, overrides?: CallOverrides): Promise<void>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDescription(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDescription(uint256,string)"(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCOO(_newCOO: string, overrides?: CallOverrides): Promise<void>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getSplashURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSplashURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;

    getDescription(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getDescription(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    updateExhibit(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateExhibit(uint256,uint256,uint256,bool,bool,string,string,string,string)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCFO(_newCFO: string, overrides?: CallOverrides): Promise<void>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSplashURI(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSplashURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    withdrawBalance(overrides?: CallOverrides): Promise<void>;

    "withdrawBalance()"(overrides?: CallOverrides): Promise<void>;

    getName(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getName(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setPublished(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPublished(uint256,bool)"(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    getExhibitsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "getExhibitsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    getAssetsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAssetsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    getCreatedAt(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCreatedAt(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createExhibit(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createExhibit(uint256,uint256,string,string,string,string)"(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getPrintsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrintsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cooAddress(overrides?: CallOverrides): Promise<string>;

    "cooAddress()"(overrides?: CallOverrides): Promise<string>;

    setAssetsTotal(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAssetsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getMetadataURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getMetadataURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    exhibits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: boolean;
      5: boolean;
      6: string;
      7: string;
      8: string;
      9: string;
    }>;

    "exhibits(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: boolean;
      5: boolean;
      6: string;
      7: string;
      8: string;
      9: string;
    }>;

    getActive(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getActive(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getExhibit(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: boolean;
      4: boolean;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;

    "getExhibit(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      assetsTotal: BigNumber;
      printsTotal: BigNumber;
      createdAt: BigNumber;
      published: boolean;
      active: boolean;
      name: string;
      description: string;
      splashURI: string;
      metadataURI: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: boolean;
      4: boolean;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setActive(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setActive(uint256,bool)"(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawalAddress(overrides?: CallOverrides): Promise<string>;

    "withdrawalAddress()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPrintsTotal(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPrintsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setName(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setName(uint256,string)"(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ExhibitCreated(
      id: BigNumberish | null,
      createdAt: null,
      name: null
    ): EventFilter;

    ContractUpgrade(newContract: null): EventFilter;

    Paused(): EventFilter;

    Unpaused(): EventFilter;

    Pause(): EventFilter;

    Unpause(): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    cfoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    setMetadataURI(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setMetadataURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    ceoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPublished(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPublished(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setCEO(_newCEO: string, overrides?: Overrides): Promise<BigNumber>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDescription(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDescription(uint256,string)"(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setCOO(_newCOO: string, overrides?: Overrides): Promise<BigNumber>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getSplashURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSplashURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides): Promise<BigNumber>;

    "unpause()"(overrides?: Overrides): Promise<BigNumber>;

    getDescription(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDescription(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateExhibit(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateExhibit(uint256,uint256,uint256,bool,bool,string,string,string,string)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setCFO(_newCFO: string, overrides?: Overrides): Promise<BigNumber>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSplashURI(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setSplashURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawBalance(overrides?: Overrides): Promise<BigNumber>;

    "withdrawBalance()"(overrides?: Overrides): Promise<BigNumber>;

    getName(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getName(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setPublished(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPublished(uint256,bool)"(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getExhibitsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "getExhibitsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: Overrides): Promise<BigNumber>;

    "pause()"(overrides?: Overrides): Promise<BigNumber>;

    getAssetsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAssetsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatedAt(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCreatedAt(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createExhibit(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createExhibit(uint256,uint256,string,string,string,string)"(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getPrintsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrintsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cooAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "cooAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    setAssetsTotal(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAssetsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getMetadataURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMetadataURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exhibits(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "exhibits(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getActive(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getActive(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExhibit(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExhibit(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setActive(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setActive(uint256,bool)"(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawalAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "withdrawalAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPrintsTotal(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPrintsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setName(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setName(uint256,string)"(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cfoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cfoAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMetadataURI(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMetadataURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    ceoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ceoAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPublished(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPublished(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setWithdrawalAddress(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setWithdrawalAddress(address)"(
      _newWithdrawalAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setCEO(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCEO(address)"(
      _newCEO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDescription(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDescription(uint256,string)"(
      _exhibitId: BigNumberish,
      _description: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setCOO(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCOO(address)"(
      _newCOO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getSplashURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSplashURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(overrides?: Overrides): Promise<PopulatedTransaction>;

    "unpause()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getDescription(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDescription(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateExhibit(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateExhibit(uint256,uint256,uint256,bool,bool,string,string,string,string)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _published: boolean,
      _active: boolean,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setCFO(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCFO(address)"(
      _newCFO: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSplashURI(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSplashURI(uint256,string)"(
      _exhibitId: BigNumberish,
      _splashURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawBalance(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawBalance()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getName(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getName(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setPublished(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPublished(uint256,bool)"(
      _exhibitId: BigNumberish,
      _published: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getExhibitsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getExhibitsLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(overrides?: Overrides): Promise<PopulatedTransaction>;

    "pause()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getAssetsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAssetsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCreatedAt(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCreatedAt(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createExhibit(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createExhibit(uint256,uint256,string,string,string,string)"(
      _assetsTotal: BigNumberish,
      _printsTotal: BigNumberish,
      _name: string,
      _description: string,
      _splashURI: string,
      _metadataURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getPrintsTotal(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPrintsTotal(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cooAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cooAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAssetsTotal(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAssetsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _assetsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getMetadataURI(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMetadataURI(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exhibits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "exhibits(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getActive(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getActive(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExhibit(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExhibit(uint256)"(
      _exhibitId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAuthorizationStatus(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAuthorizationStatus(address,bool)"(
      _authorizedAddress: string,
      _authorizedStatus: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setActive(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setActive(uint256,bool)"(
      _exhibitId: BigNumberish,
      _active: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawalAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "withdrawalAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPrintsTotal(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPrintsTotal(uint256,uint256)"(
      _exhibitId: BigNumberish,
      _printsTotal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setName(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setName(uint256,string)"(
      _exhibitId: BigNumberish,
      _name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
