/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDadaReserve } from "./IDadaReserve";

export class IDadaReserveFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDadaReserve {
    return new Contract(address, _abi, signerOrProvider) as IDadaReserve;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
    ],
    name: "acceptBidForCollectible",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minSalePriceInWei",
        type: "uint256",
      },
    ],
    name: "offerCollectibleForSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minSalePriceInWei",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
    ],
    name: "offerCollectibleForSaleToAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
    ],
    name: "withdrawOfferForCollectible",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
