/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDadaCollectible } from "./IDadaCollectible";

export class IDadaCollectibleFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDadaCollectible {
    return new Contract(address, _abi, signerOrProvider) as IDadaCollectible;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "print",
        type: "uint256",
      },
    ],
    name: "DrawingPrintToAddress",
    outputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "OfferedForSale",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
    ],
    name: "buyCollectible",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastSellValue",
        type: "uint256",
      },
    ],
    name: "makeCollectibleUnavailableToSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "drawingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "printIndex",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
