/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDadaCollectibleInterface extends ethers.utils.Interface {
  functions: {
    "DrawingPrintToAddress(uint256)": FunctionFragment;
    "buyCollectible(uint256,uint256)": FunctionFragment;
    "transfer(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DrawingPrintToAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyCollectible",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DrawingPrintToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyCollectible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;

  events: {};
}

export class IDadaCollectible extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDadaCollectibleInterface;

  functions: {
    DrawingPrintToAddress(
      print: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "DrawingPrintToAddress(uint256)"(
      print: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyCollectible(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "buyCollectible(uint256,uint256)"(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    transfer(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256,uint256)"(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DrawingPrintToAddress(
    print: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "DrawingPrintToAddress(uint256)"(
    print: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyCollectible(
    drawingId: BigNumberish,
    printIndex: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "buyCollectible(uint256,uint256)"(
    drawingId: BigNumberish,
    printIndex: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  transfer(
    to: string,
    drawingId: BigNumberish,
    printIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256,uint256)"(
    to: string,
    drawingId: BigNumberish,
    printIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DrawingPrintToAddress(
      print: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "DrawingPrintToAddress(uint256)"(
      print: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    buyCollectible(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "buyCollectible(uint256,uint256)"(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transfer(address,uint256,uint256)"(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    DrawingPrintToAddress(
      print: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "DrawingPrintToAddress(uint256)"(
      print: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyCollectible(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "buyCollectible(uint256,uint256)"(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    transfer(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256,uint256)"(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DrawingPrintToAddress(
      print: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "DrawingPrintToAddress(uint256)"(
      print: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyCollectible(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "buyCollectible(uint256,uint256)"(
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256,uint256)"(
      to: string,
      drawingId: BigNumberish,
      printIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
